/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CustomerSignupRouteImport } from './routes/customer.signup'
import { Route as ProducerIdRouteImport } from './routes/producer.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSignupRoute = CustomerSignupRouteImport.update({
  id: '/customer/signup',
  path: '/customer/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerIdRoute = ProducerIdRouteImport.update({
  id: '/producer/$id',
  path: '/producer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/profile': typeof ProfileRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/producer/$id': typeof ProducerIdRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/profile': typeof ProfileRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/producer/$id': typeof ProducerIdRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/profile': typeof ProfileRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/producer/$id': typeof ProducerIdRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/profile'
    | '/customer/signup'
    | '/producer/$id'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/profile'
    | '/customer/signup'
    | '/producer/$id'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/profile'
    | '/customer/signup'
    | '/producer/$id'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  ProfileRoute: typeof ProfileRoute
  CustomerSignupRoute: typeof CustomerSignupRoute
  ProducerIdRoute: typeof ProducerIdRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/signup': {
      id: '/customer/signup'
      path: '/customer/signup'
      fullPath: '/customer/signup'
      preLoaderRoute: typeof CustomerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/$id': {
      id: '/producer/$id'
      path: '/producer/$id'
      fullPath: '/producer/$id'
      preLoaderRoute: typeof ProducerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  ProfileRoute: ProfileRoute,
  CustomerSignupRoute: CustomerSignupRoute,
  ProducerIdRoute: ProducerIdRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
